### ISSUE TITLE
더블릿 3단계 

### ISSUE THREAD

**Issue by ppeeou** [dev-203/nodejs-study#1]
2월 5일까지 목표
하루에 5~ 10 문제 씩 풀어야함.
맞추면 체크하기
@jeoman   @hwang-taeha 
박기춘
- [x] 1 계단
- [ ] 2 계단
- [ ] 3 계단

황태하
- [x] 1 계단
- [ ] 2 계단
- [x] 3 계단

**Comment by jeoman** [comment]
<h1>hahaha</h1>
<h2>여기서도 되잖아</h2>
<p>wow very incredible</p>

**Comment by hwang-taeha** [comment]
i don't  understand....

and... how do i check??? // 영어 능력 ㅅㅌㅊ

**Comment by ppeeou** [comment]
If you should be programer, commit everyday code.

here git guide
https://backlog.com/git-tutorial/kr/intro/intro1_1.html
